ifneq ($(TARGET_SIMULATOR),true)

LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

LOCAL_SRC_FILES:= notify.c
LOCAL_MODULE := libnotify
LOCAL_C_INCLUDES += $(JNI_H_INCLUDE)
LOCAL_STATIC_LIBRARIES :=
LOCAL_SHARED_LIBRARIES := libutils
#LOCAL_CFLAGS += -Werror -Wall

LOCAL_PRELINK_MODULE := false

include $(BUILD_SHARED_LIBRARY)

endif  # TARGET_SIMULATOR != true
